// <auto-generated />
using System;
using Demo.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Demo.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250822001910_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Demo.Domain.Entites.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Discount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 8, 22, 3, 19, 10, 416, DateTimeKind.Local).AddTicks(578),
                            Description = "Bluetooth 5.0 destekli, gürültü engelleyici kulaklık.",
                            Discount = 10m,
                            IsDeleted = false,
                            Price = 700m,
                            Title = "Kablosuz Kulaklık"
                        },
                        new
                        {
                            Id = 2,
                            CreatedDate = new DateTime(2025, 8, 22, 3, 19, 10, 416, DateTimeKind.Local).AddTicks(580),
                            Description = "RGB aydınlatmalı, mavi switch mekanik klavye.",
                            Discount = 5m,
                            IsDeleted = false,
                            Price = 30000m,
                            Title = "Mekanik Klavye"
                        },
                        new
                        {
                            Id = 4,
                            CreatedDate = new DateTime(2025, 8, 22, 3, 19, 10, 416, DateTimeKind.Local).AddTicks(582),
                            Description = "Kalp ritmi ölçer, uyku takibi ve GPS destekli akıllı saat.",
                            Discount = 15m,
                            IsDeleted = false,
                            Price = 50000m,
                            Title = "Akıllı Saat"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
